-- Intentionally empty.
--
-- This migration predates the repository's `000_init` baseline, but its
-- timestamp causes Prisma to replay it after that baseline. Every change that
-- used to be declared here (customers, colors, expense budgets, the sales
-- customer relation, and the store-expense fields) is already created by
-- `000_init`. Reapplying those statements makes a fresh shadow database fail
-- on duplicate columns, tables, indexes, and constraints.
