/**
 * Color System Type Definitions
 * Single source of truth for all color-related types
 */

/**
 * Branded type for color keys
 * Ensures type safety and prevents accidental string mixing
 * Usage: ColorKey = keyof typeof COLOR_PALETTE
 */
export type ColorKey = string & { readonly __brand: "ColorKey" };

/**
 * Definition of a single color
 * Includes metadata for semantic meaning and organization
 */
export interface ColorDefinition {
  name: string;         /** Display name: "Red", "Sky Blue", etc. */
  hex: string;          /** Hex code: "#FF0000" */
  semantic?: string;    /** Semantic meaning: "error", "success", "warning", etc. */
  category?: string;    /** Category for organization: "primary", "accent", "neutral" */
  aliases?: string[];   /** Alternative names: ["danger", "critical"] for "Red" */
}

/**
 * Complete color palette
 * Record of all colors keyed by string
 * (Branded ColorKey type is used in function parameters for type safety)
 */
export type ColorPalette = Record<string, ColorDefinition>;

/**
 * Color variations for interactive states (Phase 2)
 * Generated by chroma-js in future implementation
 */
export interface ColorVariations {
  base: string;         /** Original hex color */
  tint: string;         /** Lighter version (20% white mixed) */
  shade: string;        /** Darker version (20% black mixed) */
  light: string;        /** Very light version (70% white mixed) */
  dark: string;         /** Very dark version (70% black mixed) */
  disabled: string;     /** Desaturated for disabled state */
}

/**
 * Semantic color tokens
 * Maps semantic meanings to hex values
 */
export interface SemanticColorToken {
  light: string; // Hex for light theme
  dark: string;  // Hex for dark theme
}

/**
 * NTC.js result for reverse color lookup (Phase 2)
 * Returned when converting hex → name
 */
export interface NTCResult {
  name: string;           // Detected color name
  exactMatch: boolean;    // Is exact match in palette
  distance: number;       // Distance from closest color (0-1000)
}
